[[https://melpa.org/#/eradio][file:https://melpa.org/packages/eradio-badge.svg]]

** Synopsis
eradio is a simple internet radio player for Emacs.

The public interface consists of two functions, =eradio-play= and =eradio-stop= and a variable =eradio-channels=. =eradio-play= let's you choose a radio channel to play and =eradio-stop= stops the radio player. The =eradio-channels= variable is an alist of radio channel names and their urls.

** Installation
The package is available in the Melpa repository.

*** Doom
#+begin_src lisp
;; ~/.doom.d/packages.el
(package! eradio)
#+end_src

*** use-package
#+begin_src lisp
;; ~/.emacs.d/init.el
(use-package eradio
  :ensure t)
#+end_src

** Keybindings
eradio does not bind any keybindings by default. Therefore you should bind them yourself. The following snippets are just suggestions. You can of course use any keybindings you would like.

*** Doom
#+begin_src lisp
;; ~/.doom.d/config.el
(map! :leader (:prefix ("r" . "eradio") :desc "Play a radio channel" "p" 'eradio-play))
(map! :leader (:prefix ("r" . "eradio") :desc "Stop the radio player" "s" 'eradio-stop))
#+end_src

*** Vanilla
#+begin_src lisp
;; ~/.emacs.d/init.el
(global-set-key (kbd "C-c r p") 'eradio-play)
(global-set-key (kbd "C-c r s") 'eradio-stop)
#+end_src

** Radio channels
eradio comes without any radio channels by default, but here are some of my favorites.
#+begin_src lisp
;; ~/.doom.d/config.el or ~/.emacs.d/init.el
(setq eradio-channels '(("def con - soma fm" . "https://somafm.com/defcon256.pls")          ;; electronica with defcon-speaker bumpers
                        ("metal - soma fm"   . "https://somafm.com/metal130.pls")           ;; \m/
                        ("cyberia - lainon"  . "https://lainon.life/radio/cyberia.ogg.m3u") ;; cyberpunk-esque electronica
                        ("cafe - lainon"     . "https://lainon.life/radio/cafe.ogg.m3u")))  ;; boring ambient, but with lain
#+end_src

If you are looking for something else I encourage you to check out [[https://somafm.com/][soma fm]]. They have a lot of good channels of all genres and aesthetics.
